version: '3.8'

services:
  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_DATABASE: jobplanner_BusinessCalendar
      MYSQL_USER: jobplanner_BusinessCalendar
      MYSQL_PASSWORD: Rh0r0lbk
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: Europe/Minsk
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro

  backend:
    image: vampyreqwe/business-calendar:backend
    ports:
      - "5221:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__BusinessCalendarConnectionString=server=db;database=jobplanner_BusinessCalendar;user=jobplanner_BusinessCalendar;password=Rh0r0lbk;
      - TZ=Europe/Minsk
    volumes:
      - backend_data:/app/wwwroot/images

  frontend:
    image: vampyreqwe/business-calendar:frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://jobplanner.ru
    build:
      context: ./b-calendar-frontend
      dockerfile: ./Dockerfile
      args:
       - NEXT_PUBLIC_API_URL=https://jobplanner.ru

  widget:
    image: vampyreqwe/business-calendar:widget
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

volumes:
  backend_data:
  db_data:

networks:
  default:
    name: business-calendar-network 