version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
      - widget

  backend:
    build:
      context: ./business-calendar-backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__BusinessCalendarConnectionString=server=db;database=BusinessCalendar;user=root;password=your_password;
    depends_on:
      - db
    volumes:
      - backend_data:/app/wwwroot/images

  frontend:
    build:
      context: ./b-calendar-frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production

  widget:
    build:
      context: ./booking-widget
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=BusinessCalendar
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
  backend_data: 